export const characters: Record<number, string> = {
    1: "星乃一歌",
    2: "天馬咲希",
    3: "望月穂波",
    4: "日野森志歩",
    5: "花里みのり",
    6: "桐谷遥",
    7: "桃井愛莉",
    8: "日野森雫",
    9: "小豆沢こはね",
    10: "白石杏",
    11: "東雲彰人",
    12: "青柳冬弥",
    13: "天馬司",
    14: "鳳えむ",
    15: "草薙寧々",
    16: "神代類",
    17: "宵崎奏",
    18: "朝比奈まふゆ",
    19: "東雲絵名",
    20: "暁山瑞希",
    21: "初音ミク",
    22: "鏡音リン",
    23: "鏡音レン",
    24: "巡音ルカ",
    25: "MEIKO",
    26: "KAITO",
}

export const units: Record<string, string> = {
    "light_sound": "Leo/need",
    "idol": "MORE MORE JUMP！",
    "street": "Vivid BAD SQUAD",
    "theme_park": "Wonderlands×Showtime",
    "school_refusal": "25时，在Night Code。",
}